# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bloomy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bloomy
  pod 'SwiftLint'
 
  target 'BloomyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BloomyUITests' do
    # Pods for testing
  end

end
